---
- name: Install prerequisites
  apt:
    pkg:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    update_cache: yes

- name: Add key for Caddy repo
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    state: present
    keyring: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Add Caddy repo
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present
    filename: caddy-stable

- name: Install Caddy
  apt:
    name: caddy
    state: present
    update_cache: yes

- name: Create self-signed certificate
  command: >
    openssl req -x509 -nodes -days 365
    -newkey rsa:2048
    -keyout /etc/caddy/certs/{{ domain_name }}.key
    -out /etc/caddy/certs/{{ domain_name }}.crt
    -subj "/CN={{ domain_name }}"
  args:
    creates: /etc/caddy/certs/{{ domain_name }}.crt

- name: Deploy index.html
  copy:
    src: index.html
    dest: /usr/share/caddy/index.html
    owner: caddy
    group: caddy
    mode: '0644'

- name: Deploy Caddy config
  template:
    src: templates/Caddyfile.j2
    dest: /etc/caddy/Caddyfile

- name: Ensure Caddy service is running
  service:
    name: caddy
    state: restarted
    enabled: yes
